# Generated by Django 4.1.1 on 2022-09-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_kategoria_produkty_kategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producent',
            options={'verbose_name': 'Producent', 'verbose_name_plural': 'Producenci'},
        ),
    ]
